from django.conf import settings

from .constants import PACKAGE_NAME


STRIPE_LOGGER_NAME = getattr(settings, "STRIPE_LOGGER_NAME", PACKAGE_NAME)

STRIPE_FACADE_CLASS_PATH = getattr(
    settings, "STRIPE_FACADE_CLASS_PATH", f"{PACKAGE_NAME}.facade.Facade"
)

STRIPE_API_VERSION = getattr(settings, "STRIPE_API_VERSION", "2025-06-30.basil")

STRIPE_PUBLISHABLE_KEY = getattr(settings, "STRIPE_PUBLISHABLE_KEY", None)
STRIPE_SECRET_KEY = getattr(settings, "STRIPE_SECRET_KEY", None)

STRIPE_REDIRECT_FROM_BACKEND = getattr(settings, "STRIPE_REDIRECT_FROM_BACKEND", True)

STRIPE_RETURN_URL_BASE = getattr(
    settings, "STRIPE_RETURN_URL_BASE", "http://localhost/"
)
STRIPE_ORDER_PREVIEW_URL = getattr(settings, "STRIPE_ORDER_PREVIEW_URL", None)
STRIPE_WEBHOOK_URL = getattr(settings, "STRIPE_WEBHOOK_URL", None)
STRIPE_WAITING_FOR_PAYMENT_URL = getattr(
    settings, "STRIPE_WAITING_FOR_PAYMENT_URL", None
)
STRIPE_PAYMENT_STATUS_URL = getattr(settings, "STRIPE_PAYMENT_STATUS_URL", None)
STRIPE_ORDER_CONFIRMATION_URL = getattr(settings, "STRIPE_ORDER_CONFIRMATION_URL", None)
STRIPE_CANCEL_URL = getattr(settings, "STRIPE_CANCEL_URL", None)

STRIPE_USE_PRICES_API = getattr(settings, "STRIPE_USE_PRICES_API", True)

STRIPE_COMPRESS_TO_ONE_LINE_ITEM = getattr(
    settings, "STRIPE_COMPRESS_TO_ONE_LINE_ITEM", False
)

STRIPE_ENABLE_TAX_COMPUTATION = getattr(
    settings, "STRIPE_ENABLE_TAX_COMPUTATION", False
)
STRIPE_DEFAULT_PRODUCT_TAX_CODE = getattr(
    settings, "STRIPE_DEFAULT_PRODUCT_TAX_CODE", None
)
STRIPE_DEFAULT_SHIPPING_TAX_CODE = getattr(
    settings, "STRIPE_DEFAULT_SHIPPING_TAX_CODE", "txcd_92010001"
)
# See: https://docs.stripe.com/tax/tax-codes?tax_code=shipping

STRIPE_BYPASS_ORDER_PREVIEW = getattr(settings, "STRIPE_BYPASS_ORDER_PREVIEW", False)
STRIPE_WAIT_FOR_PAYMENT_CONFIRMATION = getattr(
    settings, "STRIPE_WAIT_FOR_PAYMENT_CONFIRMATION", True
)
STRIPE_WEBHOOK_ENDPOINT_SECRET = getattr(
    settings, "STRIPE_WEBHOOK_ENDPOINT_SECRET", None
)
STRIPE_PAYMENT_POLLING_INTERVAL = getattr(
    settings, "STRIPE_PAYMENT_POLLING_INTERVAL", 1000  # in milliseconds
)

STRIPE_ENABLE_INVOICE_GENERATION = getattr(
    settings, "STRIPE_ENABLE_INVOICE_GENERATION", False
)
STRIPE_INVOICE_DISPLAY_TAX_AMOUNTS = getattr(
    settings, "STRIPE_INVOICE_DISPLAY_TAX_AMOUNTS", True
)
STRIPE_INVOICE_DESCRIPTION = getattr(settings, "STRIPE_INVOICE_DESCRIPTION", "")
STRIPE_INVOICE_FOOTER = getattr(settings, "STRIPE_INVOICE_FOOTER", "")
